- set failed state on upgrade, if package reopen failed, otherwise the upgraded   package is lost completely from rpmdb:
Installing set #2
Processing dependencies...
dcdb-api-4.0-0.30.noarch obsoleted by dcdb-api-4.0-0.31.noarch
dcdb-ss-4.0-0.30.noarch obsoleted by dcdb-ss-4.0-0.31.noarch
dcdb-cm-4.0-0.43.noarch obsoleted by dcdb-cm-4.0-0.44.noarch
dcdb-common-4.0-0.24.noarch obsoleted by dcdb-common-4.0-0.25.noarch
dcdb-mm-4.0-0.9.noarch obsoleted by dcdb-mm-4.0-0.10.noarch
dcdb-mvc-4.0-0.13.noarch obsoleted by dcdb-mvc-4.0-0.14.noarch
dcdb-pp-4.0-0.1.noarch obsoleted by dcdb-pp-4.0-0.3.noarch
There are 7 packages to install, 7 to remove:
I dcdb-api-4.0-0.31.noarch, dcdb-cm-4.0-0.44.noarch, dcdb-common-4.0-0.25.noarch, dcdb-mm-4.0-0.10.noarch, dcdb-mvc-4.0-0.14.noarch,
I dcdb-pp-4.0-0.3.noarch, dcdb-ss-4.0-0.31.noarch
R dcdb-api-4.0-0.30.noarch, dcdb-cm-4.0-0.43.noarch, dcdb-common-4.0-0.24.noarch, dcdb-mm-4.0-0.9.noarch, dcdb-mvc-4.0-0.13.noarch,
R dcdb-pp-4.0-0.1.noarch, dcdb-ss-4.0-0.30.noarch
Need to get 399.5KB of archives. After unpacking 1.8MB will be used.
Executing sudo /bin/rpm --upgrade -vh --root /...
Preparing...                ########################################### [100%]
Repackaging...
   1:dcdb-mm                ########################################### [ 14%]
   2:dcdb-cm                ########################################### [ 29%]
   3:dcdb-common            ########################################### [ 43%]
   4:dcdb-ss                ########################################### [ 57%]
   5:dcdb-api               ########################################### [ 71%]
   6:dcdb-mvc               ########################################### [ 86%]
   7:dcdb-pp                ########################################### [100%]
Upgrading...
   1:dcdb-mvc               ########################################### [ 14%]
   2:dcdb-api               ########################################### [ 29%]
Creating initial schema using /usr/share/dcdb/sql/patches/01_version.sql
Execute database file: /usr/share/dcdb/sql/patches/01_version.sql
Executed 2 statements, 0 warnings. 1 rows affected (0.00 sec).
* Applying patch: 2
Execute database file: /usr/share/dcdb/sql/patches/02_cleanup.sql
Executed 12 statements, 0 warnings. 31 rows affected (0.20 sec).
* Applying patch: 3
Execute database file: /usr/share/dcdb/sql/patches/03_version4.php
Executed 14 statements, 1 warnings. 676670 rows affected (83.71 sec).
* Applying patch: 4
Execute database file: /usr/share/dcdb/sql/patches/04_data_migration.sql
Executed 12 statements, 0 warnings. 178459 rows affected (14.22 sec).
* Your database is now up-to-date
error: open of /home/glen/rpm/delfi/RPMS//dcdb-common-4.0-0.25.noarch.rpm failed: No such file or directory
error: open of /home/glen/rpm/delfi/RPMS//dcdb-cm-4.0-0.44.noarch.rpm failed: No such file or directory
error: open of /home/glen/rpm/delfi/RPMS//dcdb-mm-4.0-0.10.noarch.rpm failed: No such file or directory
error: open of /home/glen/rpm/delfi/RPMS//dcdb-ss-4.0-0.31.noarch.rpm failed: No such file or directory
error: open of /home/glen/rpm/delfi/RPMS//dcdb-pp-4.0-0.3.noarch.rpm failed: No such file or directory
Reloading Apache 1.3 Web Server service............................[ DONE ]
Reloading Apache 1.3 Web Server service............................[ DONE ]
Installing set #3

Changed files:
    rpm-set-failed-on-reopen.patch -> 1.1.2.1